//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Boleta
    {
        public Boleta()
        {
            this.CarroCompras = new HashSet<CarroCompras>();
        }
    
        public int idBoleta { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<int> PtosAcumulados { get; set; }
        public Nullable<int> idUsuario { get; set; }
    
        public virtual Usuario Usuario { get; set; }
        public virtual ICollection<CarroCompras> CarroCompras { get; set; }
    }
}
