//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarroCompras
    {
        public Nullable<int> idBoleta { get; set; }
        public Nullable<int> idProducto { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public int idCarroCompra { get; set; }
    
        public virtual Boleta Boleta { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
