//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AccesoDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.CarroCompras = new HashSet<CarroCompras>();
        }
    
        public int idProducto { get; set; }
        public string Nombre { get; set; }
        public Nullable<int> Precio { get; set; }
        public Nullable<int> PtosCompra { get; set; }
        public Nullable<int> PtosCanje { get; set; }
        public Nullable<int> idTipoProd { get; set; }
    
        public virtual ICollection<CarroCompras> CarroCompras { get; set; }
        public virtual TipoProducto TipoProducto { get; set; }
    }
}
